# this build is designed to replicate the Travis CI workflow
name: Build with Maven

on:
  push:
    branches: [ gh-test ]
  pull_request:
    branches: [ gh-test ]
  workflow_dispatch:

jobs:                                                                                                                                              
  build:                                                                                                                                           
    uses: wikumChamith/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@backend-module                                          
    with:                                                                                                                                          
      java_versions: '[8, 11, 17]'                                                                                                           
      main_java_version: '17'        
