name: Build with Maven

on:
  push:
    branches: [ codecov ]
  pull_request:
    branches: [ codecov ]
  workflow_dispatch:

jobs:
  build:
    uses: wikumChamith/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@codecov
    with:
      java_versions: '[8, 11, 17, 21]'
      main_java_version: '8'
