name: Build with Maven

on:
  push:
    branches: [ owsap ]
  pull_request:
    branches: [ owsap ]
  workflow_dispatch:

jobs:
  build:
    uses: wikumChamith/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@owasp-test
    with:
      java_versions: '[8, 11, 17, 21]'
      main_java_version: '8'
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
